service: default
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
api_version: 1
threadsafe: yes

runtime_config:
  python_version: 3

handlers:
- url: .*
  script: main.app
  secure: always